--------------------------------------------------------
--  DDL for Table ATS
--------------------------------------------------------

  CREATE TABLE "ATS" 
   (	"AT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AT_GROUP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   );
  GRANT DELETE ON "ATS" TO "PSADMIN";
  GRANT INSERT ON "ATS" TO "PSADMIN";
  GRANT SELECT ON "ATS" TO "PSADMIN";
  GRANT UPDATE ON "ATS" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table HASHTAGS
--------------------------------------------------------

  CREATE TABLE "HASHTAGS" 
   (	"TWITTER_HANDLE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAG" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   );
  GRANT DELETE ON "HASHTAGS" TO "PSADMIN";
  GRANT INSERT ON "HASHTAGS" TO "PSADMIN";
  GRANT SELECT ON "HASHTAGS" TO "PSADMIN";
  GRANT UPDATE ON "HASHTAGS" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table HASHTAGS_REPLIES_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "HASHTAGS_REPLIES_SENTIMENT" 
   (	"HASHTAG" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNT" NUMBER(*,0)
   );
--------------------------------------------------------
--  DDL for Table HASHTAGS_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "HASHTAGS_SENTIMENT" 
   (	"HASHTAG" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNT" NUMBER(*,0)
   );
--------------------------------------------------------
--  DDL for Table INTERACTION_TWEETS
--------------------------------------------------------

  CREATE TABLE "INTERACTION_TWEETS" 
   (	"TWEET_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DO_RT" NUMBER DEFAULT 1, 
	"DO_LIKE" NUMBER DEFAULT 1
   );
--------------------------------------------------------
--  DDL for Table KEYWORDS
--------------------------------------------------------

  CREATE TABLE "KEYWORDS" 
   (	"KEYWORD" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"KEYWORD_GROUP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FACEBOOK_KEYWORD" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   );
  GRANT DELETE ON "KEYWORDS" TO "PSADMIN";
  GRANT INSERT ON "KEYWORDS" TO "PSADMIN";
  GRANT SELECT ON "KEYWORDS" TO "PSADMIN";
  GRANT UPDATE ON "KEYWORDS" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table OAC_KEYWORDS
--------------------------------------------------------

  CREATE TABLE "OAC_KEYWORDS" 
   (	"KEYWORD" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"KEYWORD_OVERLOADED" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DTIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   );
  GRANT DELETE ON "OAC_KEYWORDS" TO "PSADMIN";
  GRANT INSERT ON "OAC_KEYWORDS" TO "PSADMIN";
  GRANT SELECT ON "OAC_KEYWORDS" TO "PSADMIN";
  GRANT UPDATE ON "OAC_KEYWORDS" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table PSN_HASHTAGS
--------------------------------------------------------

  CREATE TABLE "PSN_HASHTAGS" 
   (	"NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DTIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   );
  GRANT DELETE ON "PSN_HASHTAGS" TO "PSADMIN";
  GRANT INSERT ON "PSN_HASHTAGS" TO "PSADMIN";
  GRANT SELECT ON "PSN_HASHTAGS" TO "PSADMIN";
  GRANT UPDATE ON "PSN_HASHTAGS" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table PUBLIC_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "PUBLIC_SENTIMENT" 
   (	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TWITTER_HANDLE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWITTER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET_PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOW_POSITIVE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOW_NEUTRAL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOW_NEGATIVE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" DATE, 
	"DEVICE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NUM_RTS" NUMBER(*,0), 
	"NUM_LIKES" NUMBER(*,0), 
	"NUM_REPLIES" NUMBER(*,0), 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RT_DATE" DATE, 
	"ORIGINAL_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '0', 
	"ORIGINAL_LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   );

--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "TASK" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TWITTER_ACCOUNT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_DUE" DATE, 
	"VCOMMENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DTIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   );
  GRANT DELETE ON "TASK" TO "PSADMIN";
  GRANT INSERT ON "TASK" TO "PSADMIN";
  GRANT SELECT ON "TASK" TO "PSADMIN";
  GRANT UPDATE ON "TASK" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table TASK2
--------------------------------------------------------

  CREATE TABLE "TASK2" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TWITTER_ACCOUNT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EXECUTED_DATE" DATE, 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"VCOMMENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DTIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   );
  GRANT DELETE ON "TASK2" TO "PSADMIN";
  GRANT INSERT ON "TASK2" TO "PSADMIN";
  GRANT SELECT ON "TASK2" TO "PSADMIN";
  GRANT UPDATE ON "TASK2" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table TWEETS
--------------------------------------------------------

  CREATE TABLE "TWEETS" 
   (	"TWITTER_HANDLE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOW_POSITIVE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOW_NEUTRAL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOW_NEGATIVE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETRIEVED_DATE" DATE, 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" DATE, 
	"CONTAINS_URL" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCES_OTHER_TWEETS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"POSSIBLY_SENSITIVE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"DEVICE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NUM_RTS" NUMBER(*,0), 
	"NUM_LIKES" NUMBER(*,0), 
	"NUM_REPLIES" NUMBER(*,0), 
	"NUM_QUOTES" NUMBER(*,0), 
	"TWEET_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   );
--------------------------------------------------------
--  DDL for Table TWEETS_GLOBAL_KEYWORDS
--------------------------------------------------------

  CREATE TABLE "TWEETS_GLOBAL_KEYWORDS" 
   (	"KEYWORD" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"KEYWORD_OVERLOADED" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DTIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   );
  GRANT DELETE ON "TWEETS_GLOBAL_KEYWORDS" TO "PSADMIN";
  GRANT INSERT ON "TWEETS_GLOBAL_KEYWORDS" TO "PSADMIN";
  GRANT SELECT ON "TWEETS_GLOBAL_KEYWORDS" TO "PSADMIN";
  GRANT UPDATE ON "TWEETS_GLOBAL_KEYWORDS" TO "PSADMIN";
--------------------------------------------------------
--  DDL for Table TWEETS_GLOBAL_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "TWEETS_GLOBAL_SENTIMENT" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"KEY_WORDS_OFFICIAL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP" DEFAULT ''
   );
--------------------------------------------------------
--  DDL for Table TWEETS_GLOBAL_SENTIMENT_TMP
--------------------------------------------------------

  CREATE TABLE "TWEETS_GLOBAL_SENTIMENT_TMP" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   );
--------------------------------------------------------
--  DDL for Table TWEETS_REPLIES_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "TWEETS_REPLIES_SENTIMENT" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"KEY_WORDS_REPLIES" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP" DEFAULT ''
   );
--------------------------------------------------------
--  DDL for Table TWEETS_REPLIES_SENTIMENT_TMP
--------------------------------------------------------

  CREATE TABLE "TWEETS_REPLIES_SENTIMENT_TMP" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   );
--------------------------------------------------------
--  DDL for Table TWEETS_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "TWEETS_SENTIMENT" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"KEY_WORDS_OFFICIAL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP" DEFAULT ''
   ) ;
--------------------------------------------------------
--  DDL for Table TWEETS_SENTIMENT_TMP
--------------------------------------------------------

  CREATE TABLE "TWEETS_SENTIMENT_TMP" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   ) ;
--------------------------------------------------------
--  DDL for Table TWEETS_TOUSER_SENTIMENT
--------------------------------------------------------

  CREATE TABLE "TWEETS_TOUSER_SENTIMENT" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6), 
	"DATE_RW" TIMESTAMP (6), 
	"TIMEZONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CASHTAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID_STR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY" NUMBER(10,0), 
	"HOUR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"URLS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHOTOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VIDEO" NUMBER(10,0), 
	"THUMBNAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NLIKES" NUMBER(10,0), 
	"NREPLIES" NUMBER(10,0), 
	"NRETWEETS" NUMBER(10,0), 
	"QUOTE_URL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEAR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GEO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_RT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLY_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RETWEET_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_SRC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANS_DEST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH_FILTER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT_LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SENTIMENT" FLOAT(126), 
	"HOW_POSITIVE" FLOAT(126), 
	"HOW_NEUTRAL" FLOAT(126), 
	"HOW_NEGATIVE" FLOAT(126), 
	"HASHTAGS_MODIF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"KEY_WORDS_TOUSER" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP" DEFAULT ''
   );

--------------------------------------------------------
--  DDL for Index ATS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATS_PK" ON "ATS" ("AT") ;
--------------------------------------------------------
--  DDL for Index HASHTAGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HASHTAGS_PK" ON "HASHTAGS" ("TWITTER_HANDLE", "TWEET", "HASHTAG") ;
--------------------------------------------------------
--  DDL for Index PK_HASHTAGS_REPLIES_SENTIMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_HASHTAGS_REPLIES_SENTIMENT" ON "HASHTAGS_REPLIES_SENTIMENT" ("HASHTAG", "ID") ;
--------------------------------------------------------
--  DDL for Index PK_HASHTAGS_SENTIMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_HASHTAGS_SENTIMENT" ON "HASHTAGS_SENTIMENT" ("HASHTAG", "ID");
--------------------------------------------------------
--  DDL for Index PK_INTERACTION_TWEETS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_INTERACTION_TWEETS" ON "INTERACTION_TWEETS" ("TWEET_ID") ;
--------------------------------------------------------
--  DDL for Index KEYWORDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEYWORDS_PK" ON "KEYWORDS" ("KEYWORD", "KEYWORD_GROUP")  ;
--------------------------------------------------------
--  DDL for Index PK_OAC_KEYWORDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_OAC_KEYWORDS" ON "OAC_KEYWORDS" ("KEYWORD") ;
--------------------------------------------------------
--  DDL for Index PK_PSN_HASHTAGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PSN_HASHTAGS" ON "PSN_HASHTAGS" ("NAME");


--------------------------------------------------------
--  DDL for Index TASK_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TASK_ID_PK" ON "TASK" ("ID");
--------------------------------------------------------
--  DDL for Index TASK_I1
--------------------------------------------------------

  CREATE INDEX "TASK_I1" ON "TASK" ("TWITTER_ACCOUNT") ;
--------------------------------------------------------
--  DDL for Index TASK2_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TASK2_ID_PK" ON "TASK2" ("ID") ;
--------------------------------------------------------
--  DDL for Index IDX_TWEETS
--------------------------------------------------------

  CREATE INDEX "IDX_TWEETS" ON "TWEETS" ("TWITTER_HANDLE");
--------------------------------------------------------
--  DDL for Index TWEETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TWEETS_PK" ON "TWEETS" ("TWITTER_HANDLE", "TWEET") ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_GLOBAL_KEYWORDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_GLOBAL_KEYWORDS" ON "TWEETS_GLOBAL_KEYWORDS" ("KEYWORD") ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_GLOBAL_SENTIMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_GLOBAL_SENTIMENT" ON "TWEETS_GLOBAL_SENTIMENT" ("ID") ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_GLOBAL_SENTIMENT_TMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_GLOBAL_SENTIMENT_TMP" ON "TWEETS_GLOBAL_SENTIMENT_TMP" ("ID") ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_REPLIES_SENTIMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_REPLIES_SENTIMENT" ON "TWEETS_REPLIES_SENTIMENT" ("ID")  ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_REPLIES_SENTIMENT_TMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_REPLIES_SENTIMENT_TMP" ON "TWEETS_REPLIES_SENTIMENT_TMP" ("ID") ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_SENTIMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_SENTIMENT" ON "TWEETS_SENTIMENT" ("ID");
--------------------------------------------------------
--  DDL for Index PK_TWEETS_SENTIMENT_TMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_SENTIMENT_TMP" ON "TWEETS_SENTIMENT_TMP" ("ID") ;
--------------------------------------------------------
--  DDL for Index PK_TWEETS_TOUSER_SENTIMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TWEETS_TOUSER_SENTIMENT" ON "TWEETS_TOUSER_SENTIMENT" ("ID")  ;

--------------------------------------------------------
--  Constraints for Table ATS
--------------------------------------------------------

  ALTER TABLE "ATS" ADD CONSTRAINT "ATS_PK" PRIMARY KEY ("AT")
  USING INDEX "ATS_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HASHTAGS
--------------------------------------------------------

  ALTER TABLE "HASHTAGS" ADD CONSTRAINT "HASHTAGS_PK" PRIMARY KEY ("TWITTER_HANDLE", "TWEET", "HASHTAG");
--------------------------------------------------------
--  Constraints for Table HASHTAGS_REPLIES_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "HASHTAGS_REPLIES_SENTIMENT" ADD CONSTRAINT "PK_HASHTAGS_REPLIES_SENTIMENT" PRIMARY KEY ("HASHTAG", "ID");
--------------------------------------------------------
--  Constraints for Table HASHTAGS_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "HASHTAGS_SENTIMENT" ADD CONSTRAINT "PK_HASHTAGS_SENTIMENT" PRIMARY KEY ("HASHTAG", "ID");

--------------------------------------------------------
--  Constraints for Table KEYWORDS
--------------------------------------------------------

  ALTER TABLE "KEYWORDS" ADD CONSTRAINT "KEYWORDS_PK" PRIMARY KEY ("KEYWORD", "KEYWORD_GROUP");
--------------------------------------------------------
--  Constraints for Table OAC_KEYWORDS
--------------------------------------------------------

  ALTER TABLE "OAC_KEYWORDS" ADD CONSTRAINT "PK_OAC_KEYWORDS" PRIMARY KEY ("KEYWORD");
--------------------------------------------------------
--  Constraints for Table PSN_HASHTAGS
--------------------------------------------------------

  ALTER TABLE "PSN_HASHTAGS" ADD CONSTRAINT "PK_PSN_HASHTAGS" PRIMARY KEY ("NAME");
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "TASK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TASK" ADD CONSTRAINT "TASK_ID_PK" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table TASK2
--------------------------------------------------------

  ALTER TABLE "TASK2" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TASK2" ADD CONSTRAINT "TASK2_ID_PK" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table TWEETS_GLOBAL_KEYWORDS
--------------------------------------------------------

  ALTER TABLE "TWEETS_GLOBAL_KEYWORDS" ADD CONSTRAINT "PK_TWEETS_GLOBAL_KEYWORDS" PRIMARY KEY ("KEYWORD");
--------------------------------------------------------
--  Constraints for Table TWEETS_GLOBAL_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "TWEETS_GLOBAL_SENTIMENT" ADD CONSTRAINT "PK_TWEETS_GLOBAL_SENTIMENT" PRIMARY KEY ("ID")
  USING INDEX "PK_TWEETS_GLOBAL_SENTIMENT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TWEETS_GLOBAL_SENTIMENT_TMP
--------------------------------------------------------

  ALTER TABLE "TWEETS_GLOBAL_SENTIMENT_TMP" ADD CONSTRAINT "PK_TWEETS_GLOBAL_SENTIMENT_TMP" PRIMARY KEY ("ID")
  USING INDEX "PK_TWEETS_GLOBAL_SENTIMENT_TMP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TWEETS_REPLIES_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "TWEETS_REPLIES_SENTIMENT" ADD CONSTRAINT "PK_TWEETS_REPLIES_SENTIMENT" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table TWEETS_REPLIES_SENTIMENT_TMP
--------------------------------------------------------

  ALTER TABLE "TWEETS_REPLIES_SENTIMENT_TMP" ADD CONSTRAINT "PK_TWEETS_REPLIES_SENTIMENT_TMP" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table TWEETS_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "TWEETS_SENTIMENT" ADD CONSTRAINT "PK_TWEETS_SENTIMENT" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table TWEETS_SENTIMENT_TMP
--------------------------------------------------------

  ALTER TABLE "TWEETS_SENTIMENT_TMP" ADD CONSTRAINT "PK_TWEETS_SENTIMENT_TMP" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table TWEETS_TOUSER_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "TWEETS_TOUSER_SENTIMENT" ADD CONSTRAINT "PK_TWEETS_TOUSER_SENTIMENT" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Ref Constraints for Table HASHTAGS_REPLIES_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "HASHTAGS_REPLIES_SENTIMENT" ADD CONSTRAINT "FK_HASHTAGS_REPLIES_SENTIMENT" FOREIGN KEY ("ID")
	  REFERENCES "TWEETS_REPLIES_SENTIMENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HASHTAGS_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "HASHTAGS_SENTIMENT" ADD CONSTRAINT "FK_HASHTAGS_SENTIMENT" FOREIGN KEY ("ID")
	  REFERENCES "TWEETS_SENTIMENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "TASK" ADD CONSTRAINT "TASK_TWITTER_ACCOUNT_FK" FOREIGN KEY ("TWITTER_ACCOUNT")
	  REFERENCES "ATS" ("AT") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TWEETS_REPLIES_SENTIMENT
--------------------------------------------------------

  ALTER TABLE "TWEETS_REPLIES_SENTIMENT" ADD CONSTRAINT "FK_TWEETS_REPLIES_SENTIMENT" FOREIGN KEY ("CONVERSATION_ID")
	  REFERENCES "TWEETS_SENTIMENT" ("ID") ON DELETE CASCADE ENABLE;
